# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBookStore', '0002_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='uploads/books/photos/'),
        ),
    ]
