# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 04:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBookStore', '0010_auto_20170429_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='user',
        ),
        migrations.RemoveField(
            model_name='book',
            name='users',
        ),
        migrations.DeleteModel(
            name='UserBook',
        ),
        migrations.AddField(
            model_name='profilebook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBookStore.Book'),
        ),
        migrations.AddField(
            model_name='profilebook',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBookStore.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='books',
            field=models.ManyToManyField(related_name='user_by', through='SimpleBookStore.ProfileBook', to='SimpleBookStore.Book'),
        ),
    ]
